### ISSUE TITLE
api upload tests failing with `scality-artesca-remote`

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/files_primary_s3#564] opened 2022-05-10 06:04 UTC
The API tests started failing for `scality-artesca-remote`. Build log [here](https://drone.owncloud.com/owncloud/files_primary_s3/2918/150/15)

Most of the unexpected failures are due to temporary server crashes while uploading.

```console
{"reqId":"DFKFRXx2lDoAfhOI8o5O","level":4,"time":"2022-05-10T03:48:09+00:00","remoteAddr":"192.168.30.9","user":"Alice","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/textfile0.txt","message":"Exception: HTTP\/1.1 500 The request has failed due to a temporary failure of the server.: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"The request has failed due to a temporary failure of the server.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(243): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException()\\n#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(173): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put()\\n#2 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile()\\n#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile()\\n#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut()\\n#5 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":702}"}
{"reqId":"DFKFRXx2lDoAfhOI8o5O","level":4,"time":"2022-05-10T03:48:09+00:00","remoteAddr":"192.168.30.9","user":"Alice","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/textfile0.txt","message":"Caused by: {\"Exception\":\"OCP\\\\Files\\\\ObjectStore\\\\ObjectStoreWriteException\",\"Message\":\"The request has failed due to a temporary failure of the server.\",\"Code\":503,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/ObjectStoreStorage.php(509): OCA\\\\Files_Primary_S3\\\\S3Storage->writeObject()\\n#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Close.php(105): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->writeBack()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Close->stream_close()\\n#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(96): fclose()\\n#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Checksum.php(174): Icewind\\\\Streams\\\\Wrapper->stream_close()\\n#5 [internal function]: OC\\\\Files\\\\Stream\\\\Checksum->stream_close()\\n#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(209): fclose()\\n#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(173): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put()\\n#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile()\\n#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile()\\n#10 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut()\\n#11 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#12 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#13 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#14 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/lib\\\/s3storage.php\",\"Line\":143}"}
{"reqId":"DFKFRXx2lDoAfhOI8o5O","level":4,"time":"2022-05-10T03:48:09+00:00","remoteAddr":"192.168.30.9","user":"Alice","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/textfile0.txt","message":"Caused by: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\S3Exception\",\"Message\":\"Error executing \\\"PutObject\\\" on \\\"https:\\\/\\\/artesca.isv.scality.com\\\/owncloud-acceptance-tests-2918-148\\\/urn%3Aoid%3A2147483712\\\"; AWS HTTP error: Server error response [url] https:\\\/\\\/artesca.isv.scality.com\\\/owncloud-acceptance-tests-2918-148\\\/urn%3Aoid%3A2147483712 [status code] 503 [reason phrase] Service Unavailable ServiceUnavailable (server): The request has failed due to a temporary failure of the server. - <?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?><Error><Code>ServiceUnavailable<\\\/Code><Message>The request has failed due to a temporary failure of the server.<\\\/Message><Resource><\\\/Resource><RequestId>45b3bf068048bed6b05d<\\\/RequestId><\\\/Error>\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/WrappedHttpHandler.php(97): Aws\\\\WrappedHttpHandler->parseError()\\n#1 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(204): Aws\\\\WrappedHttpHandler->Aws\\\\{closure}(*** sensitive parameters replaced ***)\\n#2 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(169): GuzzleHttp\\\\Promise\\\\Promise::callHandler()\\n#3 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/RejectedPromise.php(42): GuzzleHttp\\\\Promise\\\\Promise::GuzzleHttp\\\\Promise\\\\{closure}(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/TaskQueue.php(48): GuzzleHttp\\\\Promise\\\\RejectedPromise::GuzzleHttp\\\\Promise\\\\{closure}(*** sensitive parameters replaced ***)\\n#5 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(248): GuzzleHttp\\\\Promise\\\\TaskQueue->run()\\n#6 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(224): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitFn()\\n#7 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(269): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#8 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(226): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitList()\\n#9 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(62): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#10 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/S3\\\/ObjectUploader.php(91): GuzzleHttp\\\\Promise\\\\Promise->wait()\\n#11 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/lib\\\/s3storage.php(137): Aws\\\\S3\\\\ObjectUploader->upload()\\n#12 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/ObjectStoreStorage.php(509): OCA\\\\Files_Primary_S3\\\\S3Storage->writeObject()\\n#13 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Close.php(105): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->writeBack()\\n#14 [internal function]: OC\\\\Files\\\\Stream\\\\Close->stream_close()\\n#15 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(96): fclose()\\n#16 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/private\\\/Files\\\/Stream\\\/Checksum.php(174): Icewind\\\\Streams\\\\Wrapper->stream_close()\\n#17 [internal function]: OC\\\\Files\\\\Stream\\\\Checksum->stream_close()\\n#18 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(209): fclose()\\n#19 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(173): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put()\\n#20 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1098): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile()\\n#21 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(504): Sabre\\\\DAV\\\\Server->createFile()\\n#22 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpPut()\\n#23 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#24 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#25 \\\/var\\\/www\\\/owncloud\\\/server\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#26 \\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#27 \\\/var\\\/www\\\/owncloud\\\/server\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#28 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/server\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/WrappedHttpHandler.php\",\"Line\":195}"}
```

**Comment by phil-davis** [comment] 2022-05-10 08:48
This tests against a server that is provided by the organisation that publishes the "Artesca" S3 storage. Usually this happens because their test server is down, not working nicely, or the access credentials that we are using have changed. It might start passing again tonight, or in the next few nights.

If it fails for a few nights in a row, then we can contact someone to get it looked at.

**Comment by kiranparajuli589** [comment] 2022-05-10 10:01
hmm ok @phil-davis. we'll check for it every morning for this sprint. If it doesn't start passing, we may have to think of something else.

**Comment by phil-davis** [comment] 2022-05-10 10:33
> If it doesn't start passing, we may have to think of something else.

We can ping people in ownCloud who will contact the server-provider.

**Comment by kiranparajuli589** [comment] 2022-05-12 05:15
failed on last nightly too https://drone.owncloud.com/owncloud/files_primary_s3/2920/148/21

**Comment by kiranparajuli589** [comment] 2022-05-16 04:24
failed again on last nightly https://drone.owncloud.com/owncloud/files_primary_s3/2925

**Comment by SwikritiT** [comment] 2022-05-17 03:15
failure is same piplines  but in `configure-app` step :

<details>
<summary> detail </summary>

```
cd /var/www/owncloud/server/apps/files_primary_s3
+ cp tests/drone/scality.config.php /var/www/owncloud/server/config
+ sed -i -e "s/owncloud/owncloud-acceptance-tests-$DRONE_BUILD_NUMBER-$DRONE_STAGE_NUMBER/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/accessKey1/$SCALITY_KEY/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/verySecretKey1/$SCALITY_SECRET_ESCAPED/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/http/https/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/scality:8000/artesca.isv.scality.com/" /var/www/owncloud/server/config/scality.config.php
+ cd /var/www/owncloud/server/
+ php occ s3:create-bucket owncloud-acceptance-tests-$DRONE_BUILD_NUMBER-$DRONE_STAGE_NUMBER --accept-warning

In WrappedHttpHandler.php line 195:
                                                                               
  Error executing "HeadBucket" on "https://artesca.isv.scality.com/owncloud-a  
  cceptance-tests-2927-148"; AWS HTTP error: Server error response [url] http  
  s://artesca.isv.scality.com/owncloud-acceptance-tests-2927-148 [status code  
  ] 503 [reason phrase] Service Temporarily Unavailable  (server): 503 Servic  
  e Unavailable -                                                              
                                                                               

In RequestException.php line 89:
                                                                               
  Server error response [url] https://artesca.isv.scality.com/owncloud-accept  
  ance-tests-2927-148 [status code] 503 [reason phrase] Service Temporarily U  
  navailable                                                                   
                                                                               

s3:create-bucket [--update-configuration] [--accept-warning] [--] <bucket>
```                                                                         
</details>

**Comment by phil-davis** [comment] 2022-05-17 03:30
I will ping someone tomorrow if it does not come back.

**Comment by SwikritiT** [comment] 2022-05-18 03:41
this is consistent these days https://drone.owncloud.com/owncloud/files_primary_s3/2928/148/18

**Comment by phil-davis** [comment] 2022-05-18 03:50
```
 Error executing "HeadBucket" on "https://artesca.isv.scality.com/owncloud-acceptance-tests-2928-148"; AWS HTTP error: Server error response 
[url] https://artesca.isv.scality.com/owncloud-acceptance-tests-2928-148 [status code] 503 [reason phrase] Service Temporarily Unavailable  (server): 503 Service Unavailable
```

@oC-Chriddel the Artesca S3 scality test server seems to have gone away again.

**Comment by phil-davis** [comment] 2022-05-18 05:47
I moved this to the Blocked column in the QA project because fixing this is out of our control.

**Comment by SwikritiT** [comment] 2022-05-19 03:40
https://drone.owncloud.com/owncloud/files_primary_s3/2929

**Comment by phil-davis** [comment] 2022-05-23 06:19
@oC-Chriddel or @micbar can you follow this up with the provider of the Artesca server please.

**Comment by grgprarup** [comment] 2022-06-08 05:00
Failed on recent nightly too: https://drone.owncloud.com/owncloud/files_primary_s3/2972

**Comment by SwikritiT** [comment] 2022-06-10 03:41
failing in recent nightly as well: https://drone.owncloud.com/owncloud/files_primary_s3/2974

**Comment by phil-davis** [comment] 2022-06-10 04:11
@oC-Chriddel @micbar do we continue trying to test on this "Artesca" S3 server?
If yes, then please follow up with the provider.
If no, then we can remove this from the nightly CI.

**Comment by oC-Chriddel** [comment] 2022-06-10 08:01
Informed Scality, but still waiting for feedback. Will push again on Monday.



Thanks,

 Christian




-- 
Store. Share. Work.
www.owncloud.com
 Christian Degen
Sr. Partner Manager
 email: ***@***.***
phone: +49 151 24504078
 ownCloud GmbH
Rathsbergstrasse 17
90411 Nuernberg, Germany
 Managing Directors: Tobias Gerlinger, Holger Dyroff
Court of Registry: Amtsgericht Nuernberg
Commercial Register No.: 28050







-----Ursprüngliche Nachricht-----
Von: Phil ***@***.***>
Gesendet: Freitag 10. Juni 2022 6:11
An: owncloud/files_primary_s3 ***@***.***>
CC: Christian Degen ***@***.***>; Mention ***@***.***>
Betreff: Re: [owncloud/files_primary_s3] api upload tests failing with `scality-artesca-remote` (Issue #564)


@oC-Chriddel @micbar do we continue trying to test on this "Artesca" S3 server?
If yes, then please follow up with the provider.
If no, then we can remove this from the nightly CI.

**Comment by phil-davis** [comment] 2022-06-27 05:42
The Artesca test pipelines have been removed in PR #575 

If the test server comes back some day, then just revert that PR.

**Comment by SwikritiT** [comment] 2022-07-11 03:30
Similar failure now in `api-scal8-remote` : https://drone.owncloud.com/owncloud/files_primary_s3/3024/93/18

```console
+ cd /var/www/owncloud/server/apps/files_primary_s3
+ cp tests/drone/scality.config.php /var/www/owncloud/server/config
+ sed -i -e "s/owncloud/owncloud-acceptance-tests-$DRONE_BUILD_NUMBER-$DRONE_STAGE_NUMBER/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/accessKey1/$SCALITY_KEY/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/verySecretKey1/$SCALITY_SECRET_ESCAPED/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/http/https/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/scality:8000/s3-b.isv.scality.com/" /var/www/owncloud/server/config/scality.config.php
+ cd /var/www/owncloud/server/
+ php occ s3:create-bucket owncloud-acceptance-tests-$DRONE_BUILD_NUMBER-$DRONE_STAGE_NUMBER --accept-warning

In WrappedHttpHandler.php line 195:
                                                                               
  Error executing "HeadBucket" on "https://s3-b.isv.scality.com/owncloud-acce  
  ptance-tests-3024-93"; AWS HTTP error: Server error: `HEAD https://s3-b.isv  
  .scality.com/owncloud-acceptance-tests-3024-93` resulted in a `503 Service   
  Unavailable` response  (server): 503 Service Unavailable -                   
                                                                               

In RequestException.php line 113:
                                                                               
  Server error: `HEAD https://s3-b.isv.scality.com/owncloud-acceptance-tests-  
  3024-93` resulted in a `503 Service Unavailable` response                    
                                                                               

s3:create-bucket [--update-configuration] [--accept-warning] [--] <bucket>

```

**Comment by phil-davis** [comment] 2022-07-11 05:09
> Similar failure now in api-scal8-remote

If that keeps happening for a few days, then we will need to try and follow-up.

**Comment by phil-davis** [comment] 2022-07-12 06:04
> > Similar failure now in api-scal8-remote
> 
> If that keeps happening for a few days, then we will need to try and follow-up.

scal8 passed last night - good
https://drone.owncloud.com/owncloud/files_primary_s3/3029/92/21

**Comment by oC-Chriddel** [comment] 2022-07-13 14:41
Feedback from Scality (finally):

Hello Christian,

The server is down indeed as we're conducting a major refactoring of the S3 environment. Expect it to be up by the end of week.

This will be True for Ring & Artesca!

Best,
Christian 
-- 
Store. Share. Work.
www.owncloud.com
 Christian Degen
Sr. Partner Manager
***@***.***
phone: +49 151 24504078
 ownCloud GmbH
Rathsbergstrasse 17
90411 Nuernberg, Germany
 Managing Directors: Tobias Gerlinger, Holger Dyroff
Court of Registry: Amtsgericht Nuernberg
Commercial Register No.: 28050

Am 12.07.2022 um 08:04 schrieb Phil Davis ***@***.***>:

﻿

Similar failure now in api-scal8-remote

If that keeps happening for a few days, then we will need to try and follow-up.

scal8 passed last night - good
https://drone.owncloud.com/owncloud/files_primary_s3/3029/92/21

**Comment by sushmita56** [comment] 2022-07-18 04:02
Failed on 17 and 18 July as well
https://drone.owncloud.com/owncloud/files_primary_s3/3035
https://drone.owncloud.com/owncloud/files_primary_s3/3036

**Comment by oC-Chriddel** [comment] 2022-07-18 06:48
Received the following new credentials during the weekend. Hope this resolves the issues.



Thanks and best regards,

 Christian



Hello Christian,

Thanks for your patience.

We've now finished building our new Scality S3 testing environment. We've created a testing account for both our RING and ARTESCA on-prem S3-compatible solutions. Details are as follows:

RING endpoint: https://s3.isv.scality.com
  ARTESCA endpoint: https://artesca.isv.scality.com

RING accessKey	RING secretKey	ARTESCA accessKey	ARTESCA secretKey
0WG9ZZXJUW8G1FZ24LB9	1aKsfEO=mOVXyECIGIV37U/LGfyaOEb7ijMrcQvn	JRZFMNPAS2KSUWUK6B34	IcGlPrd3ua4O2Uqu/hGGF6Hk3eTMcxsoo5dMYtXF

You may use a client such as cyberduck or AWS CLI to create your first bucket.
Keys provided are from the root IAM account; you can create additional users in your account if needed.

Beware space is limited, please let me know if you plan to store more that 100GB of data.

Thanks,
Pierre





-- 
Store. Share. Work.
www.owncloud.com
 Christian Degen
Sr. Partner Manager
 email: ***@***.***
phone: +49 151 24504078
 ownCloud GmbH
Rathsbergstrasse 17
90411 Nuernberg, Germany
 Managing Directors: Tobias Gerlinger, Holger Dyroff
Court of Registry: Amtsgericht Nuernberg
Commercial Register No.: 28050







-----Ursprüngliche Nachricht-----
Von: Sushmita ***@***.***>
Gesendet: Montag 18. Juli 2022 6:03
An: owncloud/files_primary_s3 ***@***.***>
CC: Christian Degen ***@***.***>; Mention ***@***.***>
Betreff: Re: [owncloud/files_primary_s3] api upload tests failing with `scality-artesca-remote` (Issue #564)


Failed on 17 and 18 July as well
https://drone.owncloud.com/owncloud/files_primary_s3/3035
https://drone.owncloud.com/owncloud/files_primary_s3/3036

**Comment by kiranparajuli589** [comment] 2022-07-18 07:02
cc @phil-davis, should we try adding the Scality Artesca pipelines back in the CI?

**Comment by phil-davis** [comment] 2022-07-18 07:09
> cc @phil-davis, should we try adding the Scality Artesca pipelines back in the CI?

I will put these new keys into the drone repo settings and report back. Then we could enable the pipelines again.

**Comment by phil-davis** [comment] 2022-07-18 09:14
I am trying to work out what I have to do for `scality_secret_access_key_ring_8_escaped` - the string value has to have stuff escaped so that bash can feed it to the `sed s` substitute command.

**Comment by phil-davis** [comment] 2022-07-18 11:12
PR #587 adds the Artesca pipelines back, and adjusts the ring8 server to https://s3.isv.scality.com/ 

After merging that, we will know overnight if it is all good again.

**Comment by kiranparajuli589** [comment] 2022-07-19 04:00
The newly added pipelines were passing green on the last night CI.
Build: https://drone.owncloud.com/owncloud/files_primary_s3/3059

**Comment by phil-davis** [comment] 2022-07-19 04:01
closing - works now.

**Comment by SwikritiT** [comment] 2022-08-29 03:59
Failing in recent nightly as well: 
- https://drone.owncloud.com/owncloud/files_primary_s3/3139/149/18
- https://drone.owncloud.com/owncloud/files_primary_s3/3140
- https://drone.owncloud.com/owncloud/files_primary_s3/3141 
```console
+ cd /var/www/owncloud/server/apps/files_primary_s3
+ cp tests/drone/scality.config.php /var/www/owncloud/server/config
+ sed -i -e "s/owncloud/owncloud-acceptance-tests-$DRONE_BUILD_NUMBER-$DRONE_STAGE_NUMBER/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/accessKey1/$SCALITY_KEY/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/verySecretKey1/$SCALITY_SECRET_ESCAPED/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/http/https/" /var/www/owncloud/server/config/scality.config.php
+ sed -i -e "s/scality:8000/s3.isv.scality.com/" /var/www/owncloud/server/config/scality.config.php
+ cd /var/www/owncloud/server/
+ php occ s3:create-bucket owncloud-acceptance-tests-$DRONE_BUILD_NUMBER-$DRONE_STAGE_NUMBER --accept-warning
Creating bucket <owncloud-acceptance-tests-3139-143> ...

In WrappedHttpHandler.php line 195:
                                                                               
  Error executing "CreateBucket" on "https://s3.isv.scality.com/owncloud-acce  
  ptance-tests-3139-143"; AWS HTTP error: cURL error 60: SSL certificate prob  
  lem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-er  
  rors.html) for https://s3.isv.scality.com/owncloud-acceptance-tests-3139-14  
  3                                                                            
                                                                               

In CurlFactory.php line 211:
                                                                               
  cURL error 60: SSL certificate problem: certificate has expired (see https:  
  //curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3.isv.scality.co  
  m/owncloud-acceptance-tests-3139-143                                         
                                                                
```

**Comment by SwikritiT** [comment] 2022-08-29 04:02
> The test S3 servers that these test pipelines run against are provided by a 3rd party. They are quite often unavailable for "some time". It is possible that they come back again "soon". So I have put this in "blocked". If they don't come back Monday or Tuesday night then we can message the concerned people on Wednesday.

As mentioned in this comment we'll wait for a few days and see if this issue solves
https://github.com/owncloud/files_primary_s3/issues/602#issuecomment-1229706373

**Comment by grgprarup** [comment] 2022-08-30 03:41
Failed on Today's Nightly: https://drone.owncloud.com/owncloud/files_primary_s3/3142/144/22

**Comment by grgprarup** [comment] 2022-09-01 03:53
Failed on Today's Nightly: https://drone.owncloud.com/owncloud/files_primary_s3/3144

**Comment by phil-davis** [comment] 2022-09-01 07:28
@oC-Chriddel do you know if these S3 test servers are down again for a reason?

**Comment by oC-Chriddel** [comment] 2022-09-01 07:47
Unfortunately I don't know, but I've asked the colleagues from Scality to have a look and wait for their reply now.

**Comment by oC-Chriddel** [comment] 2022-09-01 10:03
Reply from Scality:
"Thanks for the heads up. Our certificates have expired on *.[isv.scality.com](http://isv.scality.com/).
We'll work on it and hopefully this should be fixed over the next few days."

**Comment by grgprarup** [comment] 2022-09-05 05:10
As the issue is resolved https://drone.owncloud.com/owncloud/files_primary_s3/3146. So closing this issue.

**Comment by phil-davis** [comment] 2022-09-05 05:14
Both sets of pipelines passed at the weekend:
https://drone.owncloud.com/owncloud/files_primary_s3/3147/143/21 - scality8
https://drone.owncloud.com/owncloud/files_primary_s3/3147/147/21 - scality Artesca
Good.

**Comment by grgprarup** [comment] 2022-10-28 02:51
Failing on recent nightlies:
https://drone.owncloud.com/owncloud/files_primary_s3/3238/140/18,
https://drone.owncloud.com/owncloud/files_primary_s3/3237/140/18

```feature
In WrappedHttpHandler.php line 195:
                                                                               
  Error executing "CreateBucket" on "https://s3.isv.scality.com/owncloud-acce  
  ptance-tests-3238-140"; AWS HTTP error: cURL error 60: SSL certificate prob  
  lem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-er  
  rors.html) for https://s3.isv.scality.com/owncloud-acceptance-tests-3238-14  
  0                                                                            
                                                                               

In CurlFactory.php line 211:
                                                                               
  cURL error 60: SSL certificate problem: certificate has expired (see https:  
  //curl.haxx.se/libcurl/c/libcurl-errors.html) for https://s3.isv.scality.co  
  m/owncloud-acceptance-tests-3238-140                                         
                                                                               

s3:create-bucket [--update-configuration] [--accept-warning] [--] <bucket>
```
Reopening.

**Comment by saw-jan** [comment] 2022-10-31 10:06
Looks like the certificate has expired again. This seems like a recurring issue.

**Comment by phil-davis** [comment] 2022-10-31 10:10
> This seems like a recurring issue.

Yes, and it is out of our control. @oC-Chriddel can you ping whoever manages that test server please?

**Comment by SagarGi** [comment] 2022-11-14 10:18
tests seems to be passing in nightly so this issue can be closed.

**Closed** 2022-11-14 10:18 UTC
Labels: QA-team
