### ISSUE TITLE
Lost share when transferring files to recipient

### ISSUE THREAD

**Issue by davitol** [owncloud/files_primary_s3#89] opened 2018-06-25 12:14 UTC
See https://github.com/owncloud/core/issues/31150 steps:

![screen shot 2018-06-25 at 13 22 10](https://user-images.githubusercontent.com/10596560/41849566-a4f8e7c8-7881-11e8-866f-6597a0445d99.png)

**Comment by ownclouders** [comment] 2018-06-25 12:15
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/files_primary_s3/issues/53 (Restoring a previous version of a shared file fails), https://github.com/owncloud/files_primary_s3/issues/65 (Manual Test for Files Primary S3 ), https://github.com/owncloud/files_primary_s3/issues/68 (Thumbnails are not updated when editing a file), and https://github.com/owncloud/files_primary_s3/issues/69 (Cannot upload a file of 10GB).

**Comment by PVince81** [comment] 2018-06-25 12:29
@sharidas please have a look, hope you have a docker setup.

@davitol would be good to have an acceptance test to make this fail. I know we have transfer ownership tests yet but probably don't cover your scenario.

**Comment by PVince81** [comment] 2018-06-25 12:30
setting to QA for now but no guarantee that we'll have a fix in time, so will likely because "QA known"

**Comment by PVince81** [comment] 2018-06-25 13:10
we already have acceptance tests for many cases, but probably missed this one specific share scenario: https://github.com/owncloud/core/blob/stable10/tests/acceptance/features/apiMain/transfer-ownership.feature#L5

**Comment by PVince81** [comment] 2018-06-25 13:14
estimate: 2md assuming it will likely be a small fix/tweak.

**Comment by sharidas** [comment] 2018-06-26 10:32
The issue is reproducible. It looks like the delete operation is causing the problem. I am also having a feel that I have missed the scenario where
- user1 shares a folder/file with user2
- user2 creates public link of received share
- And then execute transfer ownership command
- the public links should be accessible.

So in this case 2 shares are collected. First share is the folder/file shared by user1 to user2. Second is the public link. So when the transfer ownership command is called, the first share is processed which results in deletion of the share, since the new user or the destination user is where the share has to be moved( which it has already moved ). And while processing the second share, the `updateShare` method is called to update the target and other parameters. This is causing the exception when `getShareById` is called. Because at this point there are no shares available in the table.

**Comment by PVince81** [comment] 2018-06-26 10:41
@sharidas isn't this exactly the scenario you fixed in core already ?

Maybe here the order of the shares is different somehow which causes the deletion to happen too early ?

**Comment by sharidas** [comment] 2018-06-26 11:37
Yes. Even if the deletion is happening too early, then I am planning to have a try/catch  block when the `updateShare` is getting called. And if `ShareNotFound` exception is triggered then in the catch:
- create the share
- update the token 
- update the share again

**Comment by PVince81** [comment] 2018-06-26 13:03
@sharidas can you first confirm whether the observed problem is due to sort order of shares ?

So far I still miss the result of the analysis why your manual testing worked on the PR and why it doesn't work now in a reproducible fashion.

**Comment by PVince81** [comment] 2018-07-02 10:08
@sharidas please link the fix, declare tested and working and close

**Comment by sharidas** [comment] 2018-07-02 10:58
Changes merged in stable10 -> https://github.com/owncloud/core/pull/31953 and master branch -> https://github.com/owncloud/core/pull/31924. 
Tested and works fine ( refer the comments in the PRs ).

**Closed by sharidas** 2018-07-02 10:58 UTC
Labels: bug
