### ISSUE TITLE
files comming from skeleton have a empty version at the start

### ISSUE THREAD

**Issue by individual-it** [owncloud/files_primary_s3#161] opened 2018-12-06 04:16 UTC
1. set up a skeleton folder
2. create a new user
3. login as this new user
4. check the versions of files that came from the skeleton

There is a version listed of 0 bytes

![image](https://user-images.githubusercontent.com/2425577/49561143-c51af680-f93d-11e8-9b2c-8c2d76fb0b58.png)

That does not happen when a file is uploaded, a freshly uploaded file has no versions

**Comment by ownclouders** [comment] 2018-12-06 04:17
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/files_primary_s3/issues/66 (Initializing a new user leads to an empty version created of the skeleton file), https://github.com/owncloud/files_primary_s3/issues/53 (Restoring a previous version of a shared file fails), https://github.com/owncloud/files_primary_s3/issues/156 (restoring a version of a file does not recalculate the checksum), and https://github.com/owncloud/files_primary_s3/issues/67 (Thumbnail preview of last version of a file does not work with scality).

**Comment by davitol** [comment] 2019-10-24 06:51
@individual-it Dupe of https://github.com/owncloud/files_primary_s3/issues/66 ?

**Comment by individual-it** [comment] 2019-10-24 07:14
#66 is about the preview, but yes its related

**Comment by SagarGi** [comment] 2022-05-04 11:28
This scenario is skipped as failing on scality. https://github.com/owncloud/core/pull/40049

```console
@skipOnStorage:ceph @files_primary_s3-issue-161 @notToImplementOnOCIS @newChunking @issue-ocis-1321
@issue-ocis-reva-17 @issue-ocis-reva-56
Scenario: Uploading a file asynchronously does create the correct version that can be restored
    Given the administrator has enabled async operations
    And user "Alice" has uploaded file with content "textfile0" to "textfile0.txt"
    When user "Alice" uploads file "filesForUpload/davtest.txt" asynchronously to "textfile0.txt" in 2 chunks using the WebDAV API
    And user "Alice" uploads file "filesForUpload/lorem.txt" asynchronously to "textfile0.txt" in 2 chunks using the WebDAV API
    And user "Alice" restores version index "1" of file "/textfile0.txt" using the WebDAV API
    Then the HTTP status code of responses on all endpoints should be "202"
    And the version folder of file "/textfile0.txt" for user "Alice" should contain "2" elements
    And the content of file "/textfile0.txt" for user "Alice" should be "Dav-Test"
```

**Comment by DeepDiver1975** [comment] 2023-10-16 14:22
works as designed.

**Closed by DeepDiver1975** 2023-10-16 14:22 UTC
Labels: bug
