### ISSUE TITLE
php unit test fails in nightly

### ISSUE THREAD

**Issue by grgprarup** [owncloud/files_primary_s3#613] opened 2022-10-14 03:56 UTC
Build: https://drone.owncloud.com/owncloud/files_primary_s3/3207/5/8,
https://drone.owncloud.com/owncloud/files_primary_s3/3208/5/8
```feature
There were 4 failures:

1) Test\LargeFileHelperGetFileSizeTest::testGetFileSizeViaCurl with data set #0 ('/var/www/owncloud/server/test...em.txt', 446)
Failed asserting that null is identical to 446.

/var/www/owncloud/server/tests/lib/LargeFileHelperGetFileSizeTest.php:53

2) Test\LargeFileHelperGetFileSizeTest::testGetFileSizeViaCurl with data set #1 ('/var/www/owncloud/server/test...2).txt', 446)
Failed asserting that null is identical to 446.

/var/www/owncloud/server/tests/lib/LargeFileHelperGetFileSizeTest.php:53

3) Tests\Core\Templates\TemplatesTest::test403
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">\n
-<html><body><ul><li class="error">\n
-		Access forbidden<br><p class="hint"></p>\n
-</li></ul></body></html>\n
+<html><body><ul>\n
+<li class="error">\n
+		Access forbidden<br>\n
+		<p class="hint"></p>\n
+	</li>\n
+</ul></body></html>\n
 '

/var/www/owncloud/server/tests/lib/TestCase.php:510
/var/www/owncloud/server/tests/lib/TestCase.php:488
/var/www/owncloud/server/tests/Core/Templates/TemplatesTest.php:9

4) Tests\Core\Templates\TemplatesTest::test404
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">\n
-<html><body><ul><li class="error">\n
-			File not found<br><p class="hint">The specified document has not been found on the server.</p>\n
-<p class="hint"><a href="/owncloud/">You can click here to return to ownCloud.</a></p>\n
-		</li></ul></body></html>\n
+<html><body><ul>\n
+<li class="error">\n
+			File not found<br>\n
+			<p class="hint">The specified document has not been found on the server.</p>\n
+			<p class="hint"><a href="/owncloud/">You can click here to return to ownCloud.</a></p>\n
+		</li>\n
+	</ul></body></html>\n
 '

/var/www/owncloud/server/tests/lib/TestCase.php:510
/var/www/owncloud/server/tests/lib/TestCase.php:488
/var/www/owncloud/server/tests/Core/Templates/TemplatesTest.php:16
```
```
FAILURES!
Tests: 10626, Assertions: 59256, Failures: 4, Skipped: 125.

Generating code coverage report in Clover XML format ... done [01:26.735]
make: *** [Makefile:98: test-php-unit-dbg] Error 1
```

**Comment by kiranparajuli589** [comment] 2022-10-14 09:49
Failures separated.
```console
1) Test\LargeFileHelperGetFileSizeTest::testGetFileSizeViaCurl with data set #0 ('/var/www/owncloud/server/test...em.txt', 446)

Failed asserting that null is identical to 446.


/var/www/owncloud/server/tests/lib/LargeFileHelperGetFileSizeTest.php:53


2) Test\LargeFileHelperGetFileSizeTest::testGetFileSizeViaCurl with data set #1 ('/var/www/owncloud/server/test...2).txt', 446)

Failed asserting that null is identical to 446.


/var/www/owncloud/server/tests/lib/LargeFileHelperGetFileSizeTest.php:53


3) Tests\Core\Templates\TemplatesTest::test403

Failed asserting that two strings are equal.

--- Expected

+++ Actual

@@ @@

 '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">\n

-<html><body><ul><li class="error">\n

-		Access forbidden<br><p class="hint"></p>\n

-</li></ul></body></html>\n

+<html><body><ul>\n

+<li class="error">\n

+		Access forbidden<br>\n

+		<p class="hint"></p>\n

+	</li>\n

+</ul></body></html>\n

 '


/var/www/owncloud/server/tests/lib/TestCase.php:510

/var/www/owncloud/server/tests/lib/TestCase.php:488

/var/www/owncloud/server/tests/Core/Templates/TemplatesTest.php:9


4) Tests\Core\Templates\TemplatesTest::test404

Failed asserting that two strings are equal.

--- Expected

+++ Actual

@@ @@

 '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">\n

-<html><body><ul><li class="error">\n

-			File not found<br><p class="hint">The specified document has not been found on the server.</p>\n

-<p class="hint"><a href="/owncloud/">You can click here to return to ownCloud.</a></p>\n

-		</li></ul></body></html>\n

+<html><body><ul>\n

+<li class="error">\n

+			File not found<br>\n

+			<p class="hint">The specified document has not been found on the server.</p>\n

+			<p class="hint"><a href="/owncloud/">You can click here to return to ownCloud.</a></p>\n

+		</li>\n

+	</ul></body></html>\n

 '


/var/www/owncloud/server/tests/lib/TestCase.php:510

/var/www/owncloud/server/tests/lib/TestCase.php:488

/var/www/owncloud/server/tests/Core/Templates/TemplatesTest.php:16
```

**Comment by kiranparajuli589** [comment] 2022-10-14 10:24
Similar issue found here at https://github.com/owncloud/core/issues/38348.

**Comment by phil-davis** [comment] 2022-10-14 10:54
> Similar issue found here at [owncloud/core#38348](https://github.com/owncloud/core/issues/38348). After the base update in here https://github.com/owncloud-ci/php/blob/master/v7.4/Dockerfile.amd64, the CI has started failing again. cc @phil-davis

Hmmm - I fixed everything in core for Ubuntu 20.04 and IMO issue https://github.com/owncloud/core/issues/38348 could be closed.

This needs investigating for files_primary_s3 to understand why these tests are failing in this environment. Maybe there are clues in the core PRs linked to that issue, and maybe there is some code here in files_primary_s3 that needs similar tweaks???

**Comment by kiranparajuli589** [comment] 2022-10-14 11:17
unit tests are passing with Ubuntu 20.04 + `daily-master-qa` server but only failing with server `10.10.0-qa`.

**Comment by phil-davis** [comment] 2022-10-14 11:21
> unit tests are passing with Ubuntu 20.04 + `daily-master-qa` server but only failing with server `10.10.0-qa`.

The fixes to the core code include things like a workaround for a curl bug in the curl provided on Ubuntu 20l04 by default. Those fixes happened after core 10.10 and I expect that they are in 10.11.0.

All the mentions of `10.10.0-qa` in `.drone.star` should be bumped to `10.11.0-qa` - @kiranparajuli589 can you do that please, and then I can approve the PR.

**Comment by kiranparajuli589** [comment] 2022-10-14 11:28
yes of course @phil-davis , i'll do that asap.

**Comment by phil-davis** [comment] 2022-10-14 11:41
I merged it. If nightly CI still fails, then we can easily re-open this issue.

**Closed** 2022-10-14 11:40 UTC
Labels: QA-team

**Comment by kiranparajuli589** [comment] 2022-10-14 11:41
TODO: check the coming nightly build.

**Comment by kiranparajuli589** [comment] 2022-10-17 04:26
CI all green @ https://drone.owncloud.com/owncloud/files_primary_s3/3213. the issue is not there for 10.11.xx-qa
