### ISSUE TITLE
Php unit tests are failing in nightly CI 

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/files_primary_s3#682] opened 2023-12-15 03:40 UTC
Php unit tests are failing in following piplines
1. phpunit-scality-mbuck-cov-php7.4-10.12.0-sqlite
2. phpunit-ceph-cov-php7.4-10.12.0-sqlite
3. phpunit-ceph-cov-php7.4-10.13.0-sqlite

See build for detailed report ; https://drone.owncloud.com/owncloud/files_primary_s3/3879/8/8
```console
127) OCA\Files_Versions\Tests\VersioningTest::testStoreVersionAsRecipient with data set "metaEnabled" (true)

/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1416
/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1365
/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1329
phpvfscomposer:///var/www/owncloud/server/lib/composer/phpunit/phpunit/phpunit:97

128) OCA\Files_Versions\Tests\VersioningTest::testStoreVersionAsAnonymous with data set "metaDisabled" (false)

/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1416
/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1365
/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1356
phpvfscomposer:///var/www/owncloud/server/lib/composer/phpunit/phpunit/phpunit:97

129) OCA\Files_Versions\Tests\VersioningTest::testStoreVersionAsAnonymous with data set "metaEnabled" (true)

/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1416
/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1365
/var/www/owncloud/server/apps/files_versions/tests/VersioningTest.php:1356
phpvfscomposer:///var/www/owncloud/server/lib/composer/phpunit/phpunit/phpunit:97

OK, but incomplete, skipped, or risky tests!
Tests: 10724, Assertions: 59434, Skipped: 129.

make: *** [Makefile:98: test-php-unit-dbg] Killed
Generating code coverage report in Clover XML format ... 
```

**Comment by SwikritiT** [comment] 2023-12-15 03:41
@phil-davis can this be a aftermath of recent release?

**Comment by phil-davis** [comment] 2023-12-15 05:51
I will look.

**Comment by phil-davis** [comment] 2023-12-18 06:45
Passed over the weekend, for example:
https://drone.owncloud.com/owncloud/files_primary_s3/3886/5/8

good

**Comment by SwikritiT** [comment] 2023-12-20 03:44
similar failure in today's noghtly as well but in following pipelines
1. phpunit-scality-cov-php7.4-master-sqlite https://drone.owncloud.com/owncloud/files_primary_s3/3889/4/8
2. phpunit-scality-mbuck-cov-php7.4-master-sqlite https://drone.owncloud.com/owncloud/files_primary_s3/3889/6/8

**Comment by phil-davis** [comment] 2023-12-20 06:43
Let's keep this open and monitor for the n ext few days.
Maybe we can see some pattern that will help us find what is the root cause of the test pipeline failures.

**Comment by phil-davis** [comment] 2023-12-22 03:08
Everything passed last night, but from the previous night:
https://drone.owncloud.com/owncloud/files_primary_s3/3892/6/8
```
OK, but incomplete, skipped, or risky tests!
Tests: 10791, Assertions: 59619, Skipped: 125.

Generating code coverage report in Clover XML format ... done [01:30.727]
make: *** [Makefile:98: test-php-unit-dbg] Killed
```

The PHP unit test run did not report any individual test failures. In was generating the code coverage report, and then the pipeline was killed. But the log output does not give any reason. Mysterious.

**Comment by phil-davis** [comment] 2024-01-15 08:41
https://drone.owncloud.com/owncloud/files_primary_s3/3926
CI passed in recent nights - PHP unit tests have passed for quite a while now.
Failures are now rare. I will close this and we can open again if it fails again.

**Closed by phil-davis** 2024-01-15 08:41 UTC
Labels: QA:team
